docs/TOC.yml

From: 
https://docs.microsoft.com/en-us/dotnet/api/?redirectedfrom=MSDN
To: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.msproject?view=office-project-server

Updated "Class library and web service reference" link

---

docs/docfx.json

ms.prod should be "Office 365"

Update taxonomy for PowerBI reporting

---

docs/access/desktop-database-reference/initializing-the-microsoft-excel-driver.md

Reverts MicrosoftDocs/office-developer-client-docs#24

Revert "Deleted Microsoft/trademarks."

---

docs/access/desktop-database-reference/submacro-macro-statement.md

typo: seperate -> separate

---

docs/access/desktop-database-reference/comparison-of-microsoft-access-sql-and-ansi-sql.md
docs/access/desktop-database-reference/initializing-the-microsoft-excel-driver.md
docs/access/desktop-database-reference/initializing-the-microsoft-exchange-data-source-driver.md
docs/access/desktop-database-reference/initializing-the-text-data-source-driver.md
docs/access/desktop-database-reference/odbc-scalar-functions.md
docs/access/desktop-database-reference/sql-expressions.md
docs/access/desktop-database-reference/sql-reserved-words.md
docs/access/desktop-database-reference/using-wildcard-characters-in-string-comparisons.md

Final updates

---

docs/access/desktop-database-reference/initializing-the-microsoft-excel-driver.md

Per TASK 2805343 (OC)
Per TASK 2805116 (MAX)

merge to live

---

README.md
contributing.md

Merge 4-23 updates to live

---

docs/docfx.json

This should fix so that feedback control is only enabled on dynamic DPI article.

Fix feedback control

---

docs/TOC.yml

Change "Class library and web service ref" in TOC to Project Server 2013 class library and web service reference

Bug 3277072

---

docs/visio/how-to-manipulate-the-visio-file-format-programmatically.md

Merge 5-7 updates to live

---

docs/access/desktop-database-reference/database-openrecordset-method-dao.md

Merge to live!

---

docs/outlook/auxiliary/constants-account-management-api.md

Add ACCT_INIT_NO_NOTIFICATIONS in response to customer request

Add ACCT_INIT_NO_NOTIFICATIONS

---

docs/outlook/mapi/how-to-install-mapi-header-files.md

Update download URL

---

docs/project/developing-a-project-online-application-using-the-client-side-object-model.md

Missing code sample, added link to Office Dev Center gallery Project CSOM samples

Update Project overview doc

---

docs/visio/anglealongpath-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/anglealongpath-function

Typo "** *section* **"→"***section***"

---

docs/visio/rectsect-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/rectsect-function

Typo "** *width* **"→"***width***"

---

docs/visio/ang360-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/ang360-function

Typo "** *angle* **"→"***angle***"

---

docs/visio/arg-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/arg-function

Typo "** *argName* **"→"***argName***"

---

docs/visio/bitand-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/bitand-function

Typo "** *binarynumber1* **"→"***binarynumber1***"

---

docs/visio/asin-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/asin-function

Typo "** *number* **"→"***number***"

---

docs/access/desktop-database-reference/alter-table-statement-microsoft-access-sql.md

Corrected comment in second example

Improve / correct the comment in one of the code examples

---

docs/outlook/mapi/pidtagcontroltype-canonical-property.md

- Provide the hex value of each constant
- Remove non-existent DTCT_LISTBOX
- Add DTCT_MVLISTBOX
- Correct DTCT_MVDDLBX documentation

Update PidTagControlId documentation for correctness

---

docs/outlook/mapi/CreateMAPIInitializationMonitor.md
docs/outlook/mapi/imapiinitmonitor-beginwait.md
docs/outlook/mapi/imapiinitmonitor-isinitialized.md
docs/outlook/mapi/imapiinitmonitor-wait.md
docs/outlook/mapi/imapiinitmonitoriunknown.md
docs/outlook/mapi/imapiwaitresultiunknown.md

add IMAPIInitMonitor md files

---

docs/outlook/mapi/CreateMAPIInitializationMonitor.md
docs/outlook/mapi/mapi-functions-callbacks-and-macros.md

updated access doc landing page

[admin] merge to live

---

docs/TOC.yml
docs/access/desktop-database-reference/dbengine-idle-method-dao.md
docs/access/desktop-database-reference/enumerations-dao-reference.md
docs/access/desktop-database-reference/field-attributes-property-dao.md
docs/access/desktop-database-reference/field-type-property-dao.md
docs/outlook/auxiliary/prop_smtp_password.md
docs/shared/compatibility-between-the-32-bit-and-64-bit-versions-of-office.md
docs/shared/manageability-applications-with-the-office-365-click-to-run-installer.md

Per build report:
replaced HTML with markdown
fixed table headers
relative links

Various build fixes

---

docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md

…ce version 2109 and newer. (#353)
* Adding a section explaining OLE clients and servers behavior for Office
version 2109 and newer.
* Fixing absolute links to docs.microsoft.com
* Fix grammar.
* Addressed code review comments.
* Remove en-us from a link.
Co-authored-by: Jakub Kotynia <jakubk@microsoft.com>

[admin] publish

---

docs/visio/intersecty-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/intersecty-function
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/intersecty-function.md
#PingMSFTDocs

Typo "** *x1* **,"→"***x1***,"

---

docs/visio/year-function-visioshapesheet.md

https://docs.microsoft.com/en-us/office/client-developer/visio/year-function-visioshapesheet
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/year-function-visioshapesheet.md
#PingMSFTDocs

Typo "** *datetime* **"→"***datetime***"

---

docs/visio/strsameex-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/strsameex-function
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/strsameex-function.md
#PingMSFTDocs

Typo "** *string1* **"→"***string1***"

---

docs/excel/memory-management-in-excel.md
docs/integration/office-for-android-support-for-the-android-storage-access-framework.md
docs/outlook/auxiliary/available-events-and-their-dispids-outlook-exported-apis.md
docs/outlook/auxiliary/constants-outlook-exported-apis.md
docs/outlook/auxiliary/interfaces-account-management-api.md
docs/outlook/auxiliary/iolkenum.md
docs/outlook/auxiliary/iolkerrorunknown.md
docs/outlook/mapi/displaying-table-controls.md
docs/outlook/mapi/dtblcombobox.md
docs/outlook/mapi/dtbledit.md
docs/outlook/mapi/dtctl.md
docs/outlook/mapi/hrvalidateipmsubtree.md
docs/visio/bullet-cell-paragraph-section.md

Fix relative links
Fix description metadata
Remove HTML

[admin] fix build errors

---

docs/visio/rewiden-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/rewiden-function
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/rewiden-function.md
#PingMSFTDocs

Typo "** *srcCharSet* **"→"***srcCharSet***"

---

docs/visio/evalcell-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/evalcell-function
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/evalcell-function.md
#PingMSFTDocs

Typo "** *cellRef* **"→"***cellRef***"

---

docs/visio/intersectx-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/intersectx-function
https://github.com/MicrosoftDocs/office-developer-client-docs/edit/main/docs/visio/intersectx-function.md
#PingMSFTDocs

Typo "** *x1* **"→"***x1***"

---

docs/visio/and-function.md

https://docs.microsoft.com/en-us/office/client-developer/visio/and-function
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/and-function.md
#PingMSFTDocs

Typo "** *logical expression1* **"→"** *logical expression1* **"

---

docs/visio/second-function-visioshapesheet.md

https://docs.microsoft.com/en-us/office/client-developer/visio/second-function-visioshapesheet
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/visio/second-function-visioshapesheet.md
#PingMSFTDocs

Typo " ** *datetime* ** "→" ***datetime*** "

---

docs/outlook/mapi/how-to-choose-a-specific-version-of-mapi-to-load.md

Fix build error

---

docs/outlook/mapi/pidlidinstantmessagingaddress-canonical-property.md
docs/outlook/mapi/pidlidintendedbusystatus-canonical-property.md
docs/outlook/mapi/pidlidinternetaccountname-canonical-property.md
docs/outlook/mapi/pidlidisrecurring-canonical-property.md
docs/outlook/mapi/pidlidissilent-canonical-property.md
docs/outlook/mapi/pidlidlinkedtaskitems-canonical-property.md
docs/outlook/mapi/pidlidlocation-canonical-property.md
docs/outlook/mapi/pidlidlogdocumentposted-canonical-property.md
docs/outlook/mapi/pidlidlogdocumentprinted-canonical-property.md
docs/outlook/mapi/pidlidlogdocumentrouted-canonical-property.md
docs/outlook/mapi/pidlidlogdocumentsaved-canonical-property.md
docs/outlook/mapi/pidlidlogduration-canonical-property.md
docs/outlook/mapi/pidlidlogend-canonical-property.md
docs/outlook/mapi/pidlidlogflags-canonical-property.md
docs/outlook/mapi/pidlidlogtype-canonical-property.md
docs/outlook/mapi/pidlidlogtypedesc-canonical-property.md
docs/outlook/mapi/pidlidmeetingworkspaceurl-canonical-property.md
docs/outlook/mapi/pidlidnonsendablebcc-canonical-property.md
docs/outlook/mapi/pidlidnonsendablebcctrackstatus-canonical-property.md
docs/outlook/mapi/pidlidnonsendablecc-canonical-property.md
docs/outlook/mapi/pidlidnonsendableto-canonical-property.md
docs/outlook/mapi/pidlidnonsendcctrackstatus-canonical-property.md
docs/outlook/mapi/pidlidnonsendtotrackstatus-canonical-property.md
docs/outlook/mapi/pidlidnotecolor-canonical-property.md
docs/outlook/mapi/pidlidnotey-canonical-property.md
docs/outlook/mapi/pidlidofflinestatus-canonical-property.md
docs/outlook/mapi/pidlidownercriticalchange-canonical-property.md
docs/outlook/mapi/pidlidpagedirstream-canonical-property.md
docs/outlook/mapi/pidlidpostrsschannel-canonical-property.md
docs/outlook/mapi/pidlidprivate-canonical-property.md

This is a bulk update.
This PR is to fix issues related to missing column headers.
If these changes are not appropriate, please let me know. I'm only trying to clean up validation issues in this repo. So I can easily close this PR or modify it in whatever way is best for the content.

Message fixes | Validation issues | 4 (BULK)

---

docs/outlook/mapi/pidtagcontentconfidentialityalgorithmid-canonical-property.md
docs/outlook/mapi/pidtagcontentidentifier-canonical-property.md
docs/outlook/mapi/pidtagcontentintegritycheck-canonical-property.md
docs/outlook/mapi/pidtagcontentlength-canonical-property.md
docs/outlook/mapi/pidtagcontentreturnrequested-canonical-property.md
docs/outlook/mapi/pidtagcontentunreadcount-canonical-property.md
docs/outlook/mapi/pidtagcontrolflags-canonical-property.md
docs/outlook/mapi/pidtagcontrolid-canonical-property.md
docs/outlook/mapi/pidtagcontrolstructure-canonical-property.md
docs/outlook/mapi/pidtagconversationkey-canonical-property.md
docs/outlook/mapi/pidtagconversioneits-canonical-property.md
docs/outlook/mapi/pidtagconversionprohibited-canonical-property.md
docs/outlook/mapi/pidtagconversionwithlossprohibited-canonical-property.md
docs/outlook/mapi/pidtagconvertedeits-canonical-property.md
docs/outlook/mapi/pidtagcorrelate-canonical-property.md
docs/outlook/mapi/pidtagcorrelatemtsid-canonical-property.md
docs/outlook/mapi/pidtagcountry-canonical-property.md
docs/outlook/mapi/pidtagcreatetemplates-canonical-property.md
docs/outlook/mapi/pidtagcreationtime-canonical-property.md
docs/outlook/mapi/pidtagcustomerid-canonical-property.md
docs/outlook/mapi/pidtagdefaultpostmessageclass-canonical-property.md
docs/outlook/mapi/pidtagdefaultprofile-canonical-property.md
docs/outlook/mapi/pidtagdefaultstore-canonical-property.md
docs/outlook/mapi/pidtagdefaultviewentryid-canonical-property.md
docs/outlook/mapi/pidtagdeferreddeliverytime-canonical-property.md
docs/outlook/mapi/pidtagdeferredsendunits-canonical-property.md
docs/outlook/mapi/pidtagdeltay-canonical-property.md
docs/outlook/mapi/pidtagdiscretevalues-canonical-property.md
docs/outlook/mapi/pidtagdisplaybcc-canonical-property.md
docs/outlook/mapi/pidtagdisplayname-canonical-property.md

This is a bulk update.
This PR is to fix issues related to missing column headers.
If these changes are not appropriate, please let me know. I'm only trying to clean up validation issues in this repo. So I can easily close this PR or modify it in whatever way is best for the content.

Message fixes | Validation issues | 8 (BULK)

---

docs/visio/how-to-manipulate-the-visio-file-format-programmatically.md

**Global effort to fix broken links**
@lindalu-MSFT
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

[BrokenLinksH2] fixing broken link

---

docs/shared/compatibility-between-the-32-bit-and-64-bit-versions-of-office.md

**Global effort to fix broken links**
@lindalu-MSFT
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

[BrokenLinksH2] fixing broken links

---

docs/access/how-to-create-and-customize-a-web-app-in-access.md

[BrokenLinksH2] fix link path

---

docs/outlook/mapi/about-named-properties-used-by-outlook.md
docs/outlook/mapi/about-registering-stores-for-indexing.md
docs/outlook/mapi/about-setting-the-resolution-order-for-address-lists-in-outlook.md
docs/outlook/mapi/about-the-mapi-crash-recovery-api.md
docs/outlook/mapi/about-the-offline-state-api.md
docs/outlook/mapi/about-the-sample-wrapped-pst-store-provider.md
docs/outlook/mapi/about-the-store-api.md
docs/outlook/mapi/abproviderinit.md
docs/outlook/mapi/accelerateabsdi.md
docs/outlook/mapi/accessing-objects-by-using-the-session.md
docs/outlook/mapi/address-book-provider-sample.md
docs/outlook/mapi/allocating-and-freeing-memory-in-mapi.md
docs/outlook/mapi/api-elements-deprecated-in-this-edition.md
docs/outlook/mapi/attconversationid-and-attparentid.md
docs/outlook/mapi/attmessagestatus.md
docs/outlook/mapi/attpriority.md
docs/outlook/mapi/autocomplete-stream.md
docs/outlook/mapi/avoiding-certain-methods-at-startup.md
docs/outlook/mapi/bookmark.md
docs/outlook/mapi/building-mapi-applications-on-32-bit-and-64-bit-platforms.md
docs/outlook/mapi/callerrelease.md
docs/outlook/mapi/cbflatentry.md
docs/outlook/mapi/cbflatmtsidlist.md
docs/outlook/mapi/cbmapiforminfoarray.md
docs/outlook/mapi/cbmapiverbarray.md
docs/outlook/mapi/cbmessageclassarray.md
docs/outlook/mapi/cbnewadrlist.md
docs/outlook/mapi/cbnewentryid.md
docs/outlook/mapi/cbnewflatentry.md
docs/outlook/mapi/cbnewflatentrylist.md

[Bulk] Validation: validation fixes JM 5/27d

---

docs/outlook/mapi/imapifolder-setreadflags.md
docs/outlook/mapi/imapiform-doverb.md
docs/outlook/mapi/imapiform-getviewcontext.md
docs/outlook/mapi/imapiform-setviewcontext.md
docs/outlook/mapi/imapiformadvisesink-onactivatenext.md
docs/outlook/mapi/imapiformadvisesinkiunknown.md
docs/outlook/mapi/imapiformcontainer-getdisplay.md
docs/outlook/mapi/imapiformcontainer-installform.md
docs/outlook/mapi/imapiformcontainer-removeform.md
docs/outlook/mapi/imapiformcontainer-resolvemessageclass.md
docs/outlook/mapi/imapiformcontainer-resolvemultiplemessageclasses.md
docs/outlook/mapi/imapiformcontaineriunknown.md
docs/outlook/mapi/imapiformfactoryiunknown.md
docs/outlook/mapi/imapiforminfo-calcformpropset.md
docs/outlook/mapi/imapiforminfo-calcverbset.md
docs/outlook/mapi/imapiformiunknown.md
docs/outlook/mapi/imapiformmgr-createform.md
docs/outlook/mapi/imapiformmgr-loadform.md
docs/outlook/mapi/imapiformmgr-openformcontainer.md
docs/outlook/mapi/imapiformmgr-selectform.md
docs/outlook/mapi/imapiformmgr-selectformcontainer.md
docs/outlook/mapi/imapiformmgriunknown.md
docs/outlook/mapi/imapimessagesite-copymessage.md
docs/outlook/mapi/imapimessagesite-deletemessage.md
docs/outlook/mapi/imapimessagesite-getfolder.md
docs/outlook/mapi/imapimessagesite-getformmanager.md
docs/outlook/mapi/imapimessagesite-getmessage.md
docs/outlook/mapi/imapimessagesite-getsession.md
docs/outlook/mapi/imapimessagesite-getsitestatus.md
docs/outlook/mapi/imapimessagesite-getstore.md

[Bulk] Validation: validation fixes JM 5/31

---

docs/outlook/mapi/imapimessagesite-movemessage.md
docs/outlook/mapi/imapimessagesite-newmessage.md
docs/outlook/mapi/imapimessagesite-savemessage.md
docs/outlook/mapi/imapimessagesite-submitmessage.md
docs/outlook/mapi/imapimessagesiteiunknown.md
docs/outlook/mapi/imapiofflineiunknown.md
docs/outlook/mapi/imapiofflinemgrimapioffline.md
docs/outlook/mapi/imapiofflinenotify-notify.md
docs/outlook/mapi/imapiofflinenotifyiunknown.md
docs/outlook/mapi/imapiprogress-getflags.md
docs/outlook/mapi/imapiprogress-getmax.md
docs/outlook/mapi/imapiprogress-getmin.md
docs/outlook/mapi/imapiprogress-progress.md
docs/outlook/mapi/imapiprogress-setlimits.md
docs/outlook/mapi/imapiprogressiunknown.md
docs/outlook/mapi/imapiprop-copyprops.md
docs/outlook/mapi/imapiprop-copyto.md
docs/outlook/mapi/imapiprop-deleteprops.md
docs/outlook/mapi/imapiprop-getidsfromnames.md
docs/outlook/mapi/imapiprop-getnamesfromids.md
docs/outlook/mapi/imapiprop-getproplist.md
docs/outlook/mapi/imapiprop-getprops.md
docs/outlook/mapi/imapiprop-openproperty.md
docs/outlook/mapi/imapiprop-setprops.md
docs/outlook/mapi/imapipropiunknown.md
docs/outlook/mapi/imapisession-adminservices.md
docs/outlook/mapi/imapisession-advise.md
docs/outlook/mapi/imapisession-compareentryids.md
docs/outlook/mapi/imapisession-getmsgstorestable.md
docs/outlook/mapi/imapisession-getstatustable.md

[Bulk] Validation: validation fixes 5/31a

---

docs/outlook/mapi/display-tables.md
docs/outlook/mapi/displaying-table-rows-and-columns.md
docs/outlook/mapi/dnhier.md
docs/outlook/mapi/dntbl.md
docs/outlook/mapi/dntble.md
docs/outlook/mapi/download-hierarchy-state.md
docs/outlook/mapi/download-message-header-state.md
docs/outlook/mapi/download-table-state.md
docs/outlook/mapi/dtblbutton.md
docs/outlook/mapi/dtblcheckbox.md
docs/outlook/mapi/dtblddlbx.md
docs/outlook/mapi/dtblgroupbox.md
docs/outlook/mapi/dtblmvddlbox.md
docs/outlook/mapi/dtblmvlistbox.md
docs/outlook/mapi/dtblpage.md
docs/outlook/mapi/dtblradiobutton.md
docs/outlook/mapi/dtpage.md
docs/outlook/mapi/enableidleroutine.md
docs/outlook/mapi/entryid.md
docs/outlook/mapi/entrylist.md
docs/outlook/mapi/error-handling-in-mapi.md
docs/outlook/mapi/extended_notification.md
docs/outlook/mapi/fast-shutdown-overview.md
docs/outlook/mapi/fast-shutdown-user-options.md
docs/outlook/mapi/fbadcolumnset.md
docs/outlook/mapi/fbadentrylist.md
docs/outlook/mapi/fbadprop.md
docs/outlook/mapi/fbadproptag.md
docs/outlook/mapi/fbadrestriction.md
docs/outlook/mapi/fbadrow.md

[Bulk] Validation: validation fixes JM 5/30a

---

docs/outlook/mapi/icontabadminiunknown.md
docs/outlook/mapi/iconvertersession-setadrbook.md
docs/outlook/mapi/iconvertersession-setcharset.md
docs/outlook/mapi/iconvertersession-setencoding.md
docs/outlook/mapi/iconvertersession-setsaveformat.md
docs/outlook/mapi/iconvertersession-settextwrapping.md
docs/outlook/mapi/iconvertersessioniunknown.md
docs/outlook/mapi/idistlistimapicontainer.md
docs/outlook/mapi/idle-state.md
docs/outlook/mapi/iexchangemodifytable-gettable.md
docs/outlook/mapi/iexchangemodifytable-modifytable.md
docs/outlook/mapi/iexchangemodifytableiunknown.md
docs/outlook/mapi/imailuserimapiprop.md
docs/outlook/mapi/imapiadvisesink-onnotify.md
docs/outlook/mapi/imapiclientshutdowniunknown.md
docs/outlook/mapi/imapicontainer-getcontentstable.md
docs/outlook/mapi/imapicontainer-gethierarchytable.md
docs/outlook/mapi/imapicontainer-getsearchcriteria.md
docs/outlook/mapi/imapicontainer-setsearchcriteria.md
docs/outlook/mapi/imapicontainerimapiprop.md
docs/outlook/mapi/imapicontroliunknown.md
docs/outlook/mapi/imapifolder-copyfolder.md
docs/outlook/mapi/imapifolder-copymessages.md
docs/outlook/mapi/imapifolder-createfolder.md
docs/outlook/mapi/imapifolder-createmessage.md
docs/outlook/mapi/imapifolder-deletefolder.md
docs/outlook/mapi/imapifolder-deletemessages.md
docs/outlook/mapi/imapifolder-emptyfolder.md
docs/outlook/mapi/imapifolder-getmessagestatus.md
docs/outlook/mapi/imapifolderimapicontainer.md

[Bulk] Validation: validation fixes JM 5/30b

---

docs/outlook/mapi/cbnewflatmtsidlist.md
docs/outlook/mapi/cbnewmtsid.md
docs/outlook/mapi/cbnewspropattrarray.md
docs/outlook/mapi/cbnewspropproblemarray.md
docs/outlook/mapi/cbnewsproptagarray.md
docs/outlook/mapi/cbnewsrowset.md
docs/outlook/mapi/cbnewssortorderset.md
docs/outlook/mapi/cbspropattrarray.md
docs/outlook/mapi/cbspropproblemarray.md
docs/outlook/mapi/change_prop_type.md
docs/outlook/mapi/checkparameters.md
docs/outlook/mapi/checkparms.md
docs/outlook/mapi/client-naming-responsibilities.md
docs/outlook/mapi/client-shutdown-in-mapi.md
docs/outlook/mapi/closeimsgsession.md
docs/outlook/mapi/commonly-used-header-files.md
docs/outlook/mapi/commonly-used-objects.md
docs/outlook/mapi/commonly-used-properties.md
docs/outlook/mapi/component-object-model-and-mapi.md
docs/outlook/mapi/contab_entryid.md
docs/outlook/mapi/content-retired-notice-mapi.md
docs/outlook/mapi/contents-tables.md
docs/outlook/mapi/copying-or-moving-a-message-or-a-folder.md
docs/outlook/mapi/createiprop.md
docs/outlook/mapi/createtable.md
docs/outlook/mapi/currency.md
docs/outlook/mapi/deregisteridleroutine.md
docs/outlook/mapi/dir_entryid.md
docs/outlook/mapi/disconnecting-an-offline-state-add-in.md
docs/outlook/mapi/dismissmodeless.md

[Bulk] Validation: validation fixes JM 5/30

---

docs/outlook/mapi/imessage-deleteattach.md
docs/outlook/mapi/imessage-openattach.md
docs/outlook/mapi/imessage-setreadflag.md
docs/outlook/mapi/imessage-submitmessage.md
docs/outlook/mapi/implementing-a-logon-object.md
docs/outlook/mapi/implementing-a-service-provider-entry-point-function.md
docs/outlook/mapi/implementing-an-address-book-provider-entry-point-function.md
docs/outlook/mapi/implementing-an-advise-sink-object.md
docs/outlook/mapi/implementing-standard-form-verbs.md
docs/outlook/mapi/implementing-the-flushqueues-method.md
docs/outlook/mapi/implementing-the-iclassfactory-interface-for-form-servers.md
docs/outlook/mapi/imsgserviceadmin-adminproviders.md
docs/outlook/mapi/imsgserviceadmin-configuremsgservice.md
docs/outlook/mapi/imsgserviceadmin-createmsgservice.md
docs/outlook/mapi/imsgserviceadmin-deletemsgservice.md
docs/outlook/mapi/imsgserviceadmin-getmsgservicetable.md
docs/outlook/mapi/imsgserviceadmin-openprofilesection.md
docs/outlook/mapi/imsgserviceadmin2imsgserviceadmin.md
docs/outlook/mapi/imsgstore-abortsubmit.md
docs/outlook/mapi/imsgstore-advise.md
docs/outlook/mapi/imsgstore-compareentryids.md
docs/outlook/mapi/imsgstore-finishedmsg.md
docs/outlook/mapi/imsgstore-getreceivefolder.md
docs/outlook/mapi/imsgstore-getreceivefoldertable.md
docs/outlook/mapi/imsgstore-openentry.md
docs/outlook/mapi/imsgstore-setreceivefolder.md
docs/outlook/mapi/imsgstoreimapiprop.md
docs/outlook/mapi/imslogon-advise.md
docs/outlook/mapi/imsprovideriunknown.md
docs/outlook/mapi/initializing-a-wrapped-pst-store-provider.md

[Bulk] Validation: validation fixes JM 5/31c

---

docs/outlook/selecting-an-api-or-technology-for-developing-solutions-for-outlook.md
docs/outlook/social-connector/installation-checklist.md

Fixed broken links in Outlook folder.

[BrokenLinksH2] Fixed broken links

---

docs/TOC.yml

Fixed broken link in toc.yml file.

[BrokenLinksH2] Fixed broken link

---

docs/outlook/mapi/installing-the-sample-wrapped-pst-store-provider.md

[BrokenLinksH2] Fix path in link

---

README.md
docs/access/desktop-database-reference/concepts.md

**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

---

docs/outlook/mapi/pidtagexchangeprofilesectionid-canonical-property.md
docs/outlook/mapi/using-multiple-exchange-accounts.md
docs/outlook/pia/how-to-get-and-log-on-to-an-instance-of-outlook.md
docs/outlook/pia/how-to-get-the-e-mail-address-of-a-recipient.md
docs/outlook/pia/how-to-get-the-global-address-list-or-a-set-of-address-lists-for-a-store.md
docs/outlook/pia/how-to-modify-the-layout-of-an-electronic-business-card.md
docs/outlook/pia/how-to-search-attachments-of-items-in-a-folder-for-an-exact-phrase.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Rebranding links

---

README.md
docs/access/desktop-database-reference/concepts.md

**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

[BULK UPDATE] DocuTune - Rebranding

---

docs/docfx.json

This Pull Request was generated automatically as part of a global effort to improve metadata quality. Please review and merge this Pull Request within 5 days. If you have any questions or concerns about these metadata updates, please contact docs-allowlist-mgmt@microsoft.com. If you are not the correct contact for this content and repository, please notify Metadata-Management@microsoft.com.
Fixing[#563840 Remove ms.prod value office365](https://dev.azure.com/ceapex/Content%20Learning%20Content%20Architecture/_workitems/edit/563840)
If this Pull Request is not merged within 14 days, it will be automatically merged by our system to ensure the timeliness of the metadata update.Please notify Metadata-Management@microsoft.com if you would like Pull Requests for metadata updates to merge …

[METADATA UPDATE] Global metadata changes

---

docs/docfx.json

A Pull Request has been made from the Learn Platform's Metadata Management System to update allowlist-driven metadata. Please review and merge this Pull Request within 5 days.
If you are not the correct contact for this content and repository, please notify [Metadata-Management@microsoft.com](mailto:Metadata-Management@microsoft.com).
Please notify [Metadata-Management@microsoft.com](mailto:Metadata-Management@microsoft.com) if you have questions or concerns or would like Pull Requests for allowlist metadata updates to merge automatically in future.
If you have questions or concerns about these metadata changes, please use https://aka.ms/AllowlistFeedback or contact [docs-allowlist-mgmt@microsoft.com](mailto:docs-allowlist-mgmt@microsoft.com) to let us know.
If this Pull Request is not …

[METADATA UPDATE] Global allowlist metadata update

---

docs/visio/about-currency-constants.md
docs/visio/doclangid-cell-document-properties-section.md

This PR addresses the following Policheck bugs:
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/102125
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/102128
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/102147
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/102150
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/102167

Policheck update - August 17 | Bulk Update

---

docs/shared/Office-funciton-MsoFRequireSignedAddins.md
docs/shared/Office-function-MsoFIsFileFromTrustedLocation.md

There are metadata requirements for public API documentation tobe scaned by APIScan tool. Add the necessary metadata.

add metadata for the two function documents.

---

docs/access/desktop-database-reference/field2-iscomplex-property-dao.md

NOTE: This change will be accompanied by a change to Access code to update the help id for daproIsComplex to be 1053560

Add f1_keywords node to fix bug where F1 help for IsComplex  to address bug where F1 currently takes user to PartialReplica help (ADO.7367433)

---

docs/TOC.yml
docs/outlook/mapi/mapi-functions-callbacks-and-macros.md
docs/outlook/mapi/scmapixfromsmapi.md

Merge new file ScMAPIXFromSMAPI

---

docs/docfx.json

Also dedupe ms.service and ms.subservice, and remove empty ms.prod node

Use default feedback system

---

docs/shared/office-function-msofisfilefromtrustedlocation.md
docs/shared/office-function-msofrequiresignedaddins.md
docs/shared/office-functions-Overview.md

This PR upgrades the localization priority on every article labeled as "low".

Update localization priority

---

docs/outlook/mapi/iprofadmin-copyprofile.md
docs/outlook/mapi/iprofadmin-createprofile.md
docs/outlook/mapi/iprofadmin-deleteprofile.md
docs/outlook/mapi/iprofadmin-getprofiletable.md
docs/outlook/mapi/iprofadmin-renameprofile.md
docs/outlook/mapi/iprofadmin-setdefaultprofile.md
docs/outlook/mapi/mapilogonex.md

Document MAPI "App" Profiles
