- docs/excel/known-issues-in-excel-xll-development.md
Even if you add one or two spaces, the '.' character is still truncated. Also, if you have a function with no arguments, then it is the function help that is truncated. I've found that adding an empty string as the last "argument help" parameter of a given function registration is a better workaround. Nothing is truncated, and the '.' character is shown in all cases.
> Slightly better workaround for last arg truncation issue

- docs/outlook/auxiliary/iolkaccountmanager-init.md
The ACCT_INIT_NO_NOTIFICATIONS flag is required to allow other applications to receive broadcast messages when the Account Manager is initialized on a background thread. 
Otherwise the caller will hang.
> Document ACCT_INIT_NO_NOTIFICATIONS flag

- docs/onenote/onenote-home.md
1. Removed two links that are already available in a note box above. These links are not directly connected to the subject at hand and should be limited anyway. Without a proper description, they only confuse the developers into reading what does not apply to their cases.
2. Adjusted headings.
> Removed redudant links

- docs/outlook/pia/how-to-implement-a-wrapper-for-inspectors-and-track-item-level-events-in-each-inspector.md
From.
// wrapped TaskItem      
private Outlook.ContactItem m_Task;
To
// wrapped TaskItem      
private Outlook.TaskItem m_Task;
> Changed a typo in OutlookInspector class

- docs/excel/xleventregister.md
According to my tests, the return value (pxRes) has a type xltypeInt and is superior to 0 if success, and equal to zero if it fails. The return value  (ireturnvalue) of the function itself (int ireturnvalue=Excel12(..))  is always zero.
> [XLL] Fix information regarding the returned value

- docs/visio/angletopar-function.md
https://docs.microsoft.com/en-us/office/client-developer/visio/angletopar-function
> Typo "** *srcAngle* **"→"***srcAngle***"

- docs/visio/how-to-manipulate-the-visio-file-format-programmatically.md
By default Visio files use http for their schemas, searching for relationships using https returned null in a newly created Visio file, which made the entire tutorial not work.
> Updated schema links from https to http

- docs/access/desktop-database-reference/filter-property-ado.md
Added examples on how _not_ to use "OR" and how to do it _instead_. Those examples were introduced in the text but missing. 
As I was looking for this very specific information and found it missing, I was glad to find the answer in [filter property docs of SQL server](https://docs.microsoft.com/en-us/sql/ado/reference/ado-api/filter-property) and copied it over as it applies here as well.
> Add missing examples in filter-property-ado.md

- docs/access/desktop-database-reference/inner-join-operation-microsoft-access-sql.md
Fix the incorrect syntax example on linking multiple ON clauses.
Remove improper ON keywords next to AND/OR.
Remove unmatched parentheses and brackets.
> Fix incorrect syntax example in inner-join-operation-microsoft-access-sql.md

- docs/shared/integrating-im-applications-with-office.md
oiFeatureFreeBusyIntegration in the OIFeature is supported in Outlook for Office 365 version 2011 and higher
> reflect support for oiFeatureFreeBusyIntegration

- docs/outlook/mapi/autocomplete-stream.md
PT_ERROR is a "32-bit error value"
> Fix PT_ERROR definition in autocomplete-stream.md

- docs/access/desktop-database-reference/source-property-ado-error.md
https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/source-property-ado-error
> Typo "**ADOX.***ObjectName*"→"**ADOX.** *ObjectName*"

- docs/visio/listmembercount-function.md
If the shape is not a list container, the LISTMEMBERCOUNT function returns -1.
should read
If the shape is not a list container, the LISTMEMBERCOUNT function returns 0.
> LISTMEMBERCOUNT Return incorrect

- docs/outlook/mapi/using-a-table-to-work-with-properties.md
https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/using-a-table-to-work-with-properties
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/outlook/mapi/using-a-table-to-work-with-properties.md
#PingMSFTDocs
> Typo "** IMAPITable **"→"**IMAPITable**"

- docs/excel/functions-in-the-framework-library.md
https://docs.microsoft.com/en-us/office/client-developer/excel/functions-in-the-framework-library
https://github.com/MicrosoftDocs/office-developer-client-docs/blob/main/docs/excel/functions-in-the-framework-library.md
#PingMSFTDocs
> Typo "** Excel12 **"→"**Excel12**"

- docs/access/desktop-database-reference/ado-objects-and-interfaces.md
The "Command" anchor is linked to the Error object's page, and the "Connection" anchor is linked to the Field object's page.
> Correcting the href attribute of two anchors

- docs/outlook/mapi/constructing-entry-identifiers.md
Confer with docs/outlook/mapi/entryid.md and/or the Windows SDK (mapidefs.h) to establish that MAPI_NOTRECIP is the right name.
> Fix a spello in docs/outlook/mapi/constructing-entry-identifiers.md

- docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
Starting with version 2203, Word aligned its behavior in terms of OLE in-place activation. This is brings the documentation in-line with the behavior change.
> Update the docs OLE in-place activation now the Word supports it too

- docs/outlook/mapi/property-types.md
- docs/outlook/mapi/spropvalue.md
Editorial note:
Many hyperlinks in the existing documents use a `msdn.microsoft.com/library/` hyperlink, but I was unsure how to turn `https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/spropertyrestriction` into such a library link.
> PT_LONG is not fully usable with unsigned data

- docs/outlook/mapi/pidlidtodosubordinal-canonical-property.md
- docs/outlook/mapi/sizeddtbllabel.md
The mnemonic codes for ASCII control characters have *three*-letter codes, not 4LC. The remaining documentation here uses "null character", so be consistent in the following two files as well.
> MAPI: first character in ASCII is "NUL"

- docs/outlook/mapi/pidtagmessageflags-canonical-property.md
Updating PidTagMessageFlags with newly introduced flag MSGFLAG_ORIGIN_EXT_SEND.
The flag is used to indicate external origin of a message.
> Update PidTagMessageFlags with MSGFLAG_ORIGIN_EXT_SEND

- docs/shared/manageability-applications-with-the-office-365-click-to-run-installer.md
Updated the API information in this article with the latest API version that was recently released.  The old APIs are scheduled for deprecation.
> update to published API

- docs/outlook/mapi/imapifolder-deletefolder.md
MFCMAPI allows choosing between soft-delete and hard-delete mode when deleting a folder, i.e. setting the `DELETE_HARD_DELETE` flag bit for the `IMAPIFolder::DeleteFolder` function call. Network transmissions made by the emsmdb32.dll connector produce ropDeleteFolder requests that indeed carry the flag. The OXCROPS protocol specification for the `ropDeleteFolder` request also mentions this flag as well.
The omission of `DELETE_HARD_DELETE` in the `IMAPIFolder::DeleteFolder` documentation therefore appears accidental and is hereby rectified.
> MAPI: mention DELETE_HARD_DELETE flag for IMAPIFolder::DeleteFolder

- docs/shared/Office-funciton-MsoFRequireSignedAddins.md
- docs/shared/Office-function-MsoFIsFileFromTrustedLocation.md
- docs/shared/office-functions-Overview.md
Adding Office MSO functions in public docs to meet the requirements of the API Usage Standard of the Interoperability Policy.
> add Office MSO functions docs.

- docs/shared/office-function-msofisfilefromtrustedlocation.md
- docs/shared/office-function-msofrequiresignedaddins.md
In previous PR: https://github.com/MicrosoftDocs/office-developer-client-docs/pull/713, we got [Warning: attribute-reserved], the APILocation, APIType and APIName are reserved for use by Docs. Use "api_name", "api_type" and "api_location" instead.
> add metadata (api_name, api_type, api_location) to mso function docs.

- docs/shared/office-function-msofisfilefromtrustedlocation.md
- docs/shared/office-function-msofrequiresignedaddins.md
APIScan also requires the tag topic type to be added
> Adding topic type to API reference documentation previously added

- docs/outlook/mapi/implementing-iunknown-in-c-plus-plus.md
The current impl. is not fully thread-safe, since the `m_cRef` member might have changed by another thread since the `InterlockedDecrement` call on the line above. Suggest to instead use the `InterlockedDecrement` _return-value_ for the ref-count check to avoid this problem.
Examples of implementations already following the same pattern:
* `CComObject::Release` in atlmfc\include\atlcom.h
* `IDocument::Release` in atlmfc\include\atlhandler.h
* `CStringData::Release` in atlmfc\include\atlsimpstr.h
* `_QIThunk::Release` in atlmfc\include\atlbase.h
* [How to implement IUnknown using C++ | Pluralsight](https://www.youtube.com/watch?v=CQoZQR0vCAY)
> Implement IUnknown: Make Release method thread-safe

- docs/outlook/mapi/implementing-iunknown-in-c-plus-plus.md
Follow-up to #764. The current impl. is not fully thread-safe, since the `m_cRef` member might have changed by another thread since the `InterlockedIncrement` call on the line above. Suggest to instead return the `InterlockedIncrement` return-value to avoid this problem.
Examples of implementations already following the same pattern:
* `CComObject::AddRef` in atlmfc\include\atlcom.h
* `IDocument::AddRef` in atlmfc\include\atlhandler.h
* `CStringData::AddRef` in atlmfc\include\atlsimpstr.h
* `_QIThunk::AddRef` in atlmfc\include\atlbase.h
* How to implement IUnknown using C++ | Pluralsight: https://www.youtube.com/watch?v=CQoZQR0vCAY
> Implement IUnknown: Make AddRef thread-safe

- docs/outlook/mapi/mfcmapi-as-a-code-sample.md
Updated MFCMAPI sample link as CodePlex has been replaced by GitHub
> Update sample link for MFCMAPI from Codeplex to GitHub

- docs/outlook/mapi/address-book-provider-sample.md
- docs/outlook/mapi/downloading-the-outlook-mapi-samples.md
- docs/outlook/mapi/transport-provider-sample.md
On
https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/mapi-service-provider-samples
Says “You can download this sample from [Outlook Messaging API (MAPI) Code Samples](https://go.microsoft.com/fwlink/?LinkId=129740).”
This link should go to https://go.microsoft.com/fwlink/?LinkId=129740 
Seems to be a dead link and lands on MS main page 
Now according to the internet Archive this link should go to 
https://www.codeplex.com/OutlookMAPISample -> 301 -> https://archive.codeplex.com/?p=OutlookMAPISamples
the site now tells us that 
[https://github.com/stephenegriffin/Outlook2007CodeSamples](https://web.archive.org/web/20200722215945mp_/https:/github.com/stephenegriffin/Outlook2007CodeSamples)
	https://github.com/microsoft/Outlook2007CodeSamples/tree/main/SampleTransportPro …
> Correcting links to MAPI samples that target Deadlinks or Really old external articles to deadlinks
